# Generated by Django 5.2.7 on 2025-10-22 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('idade', models.PositiveIntegerField()),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=80)),
                ('qtd_pessoas', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(max_length=200)),
                ('nota', models.IntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='crud.pessoa')),
            ],
        ),
    ]
