# Generated by Django 5.2.7 on 2025-10-24 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_pessoa_qtd_pessoas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes', to='crud.pessoa'),
        ),
    ]
