# Generated by Django 5.2.7 on 2025-10-31 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_alter_avaliacao_pessoa_alter_pessoa_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='prato_selecionado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
